stages:
  - build
  - deploy



build:
  stage: build
  script:
    - sudo docker network rm -f mynetwork
    - sudo docker network create mynetwork
    - sudo docker rm -f nacos
    - sudo docker run -d --name nacos --network mynetwork -p 8849:8848 -e MODE=standalone nacos/nacos-server:2.0.2
    - mvn clean package
    - sudo docker build -t library-service ./library
    - sudo docker build -t gateway-service ./gateway

deploy:
  stage: deploy
  script:
    - sudo docker-compose down
    - sudo docker-compose up -d
