variables:
  GIT_REPO_URL: "http://192.168.202.220:8090/root/library.git"

stages:
  - clone
  - build
  - deploy

clone:
  stage: clone
  script:
    - git clone $GIT_REPO_URL

build:
  stage: build
  script:
    - mvn clean package
    - docker build -t library ./library
    - docker build -t gateway ./gateway

deploy:
  stage: deploy
  script:
    - docker-compose up -d
