stages:
  - build
  - deploy



build:
  stage: build
  script:
    - mvn clean package
    - sudo docker build -t library-service ./library
    - sudo docker build -t gateway-service ./gateway

deploy:
  stage: deploy
  script:
    - sudo docker-compose down
    - sudo docker-compose up -d
