image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - mvn clean package
    - docker build -t library ./library
    - docker build -t gateway ./gateway

deploy:
  stage: deploy
  script:
    - docker-compose up -d
