version: '3'
services:
  mysql:
    image: mysql:5.7.26
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "springboot-vue"
    networks:
      - mynetwork
    volumes:
      - ./library.sql:/docker-entrypoint-initdb.d/library.sql
  redis:
    image: redis:latest
    networks:
      - mynetwork

  nacos:
    image: nacos/nacos-server:2.0.2
    networks:
      - mynetwork
    environment:
      MODE: "standalone"

  library:
    image: library-service
    environment:
      MYSQL_HOST: mysql
      REDIS_HOST: redis
      NACOS_HOST: nacos
    restart: on-failure
    networks:
      - mynetwork
    ports:
      - "9200:8082"
    depends_on:
      - nacos
      - mysql
      - redis


  gateway:
      image: gateway-service
      environment:
        MYSQL_HOST: mysql
        REDIS_HOST: redis
        NACOS_HOST: nacos
      restart: on-failure
      volumes:
        - /tmp/log:/tmp
      networks:
        - mynetwork
      ports:
        - "9100:8081"
      depends_on:
        - nacos
        - mysql
        - redis

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./vue/html1:/var/www/html

networks:
  mynetwork:
