version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "springboot-vue"
    networks:
      - mynetwork
    volumes:
      - ./library.sql:/docker-entrypoint-initdb.d/library.sql
  redis:
    image: redis:latest
    networks:
      - mynetwork
  nacos:
    image: nacos/nacos-server:2.0.2
    networks:
      - mynetwork
    environment:
      MODE: "standalone"


  library:
    image: openjdk:8-jdk-alpine
    volumes:
      - ./library/target/library-0.0.1-SNAPSHOT.jar:/app/library-0.0.1-SNAPSHOT.jar
    environment:
      MYSQL_HOST: mysql
      REDIS_HOST: redis
      NACOS_HOST: nacos
    networks:
      - mynetwork
    ports:
      - 9200:8080
    depends_on:
      - nacos
      - mysql
      - redis
    command:
      - java -jar /app/library-0.0.1-SNAPSHOT.jar


  gateway:
      image: openjdk:8-jdk-alpine
      environment:
        MYSQL_HOST: mysql
        REDIS_HOST: redis
        NACOS_HOST: nacos
      networks:
        - mynetwork
      ports:
        - 9100:8080
      depends_on:
        - nacos
        - mysql
        - redis
      volumes:
        - ./gateway/target/gateway-1.0-SNAPSHOT.jar:/app/gateway-1.0-SNAPSHOT.jar
      command:
        - java -jar /app/gateway-1.0-SNAPSHOT.jar


networks:
  mynetwork:
