version: '3'
services:
  mysql:
    image: mysql:5.7.26
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "springboot-vue"
    networks:
      - mynetwork
    volumes:
      - ./library.sql:/docker-entrypoint-initdb.d/library.sql
  redis:
    image: redis:latest
    networks:
      - mynetwork



  library:
    image: library-service
    environment:
      MYSQL_HOST: mysql
      REDIS_HOST: redis
      NACOS_HOST: nacos
    restart: on-failure
    networks:
      - mynetwork
    ports:
      - "9200:8080"
    depends_on:
      - nacos
      - mysql
      - redis


  gateway:
      image: gateway-service
      environment:
        MYSQL_HOST: mysql
        REDIS_HOST: redis
        NACOS_HOST: nacos
      restart: on-failure
      networks:
        - mynetwork
      ports:
        - "9100:8080"
      depends_on:
        - nacos
        - mysql
        - redis


networks:
  mynetwork:
