server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
    gateway:
      routes:
        - id: demo-one
          uri: lb://libirary-service
          predicates:
            - Path=/**
#          predicates:
#            - Path=/api/user/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
  redis:
    port: 6379
    host: ${REDIS_HOST:localhost}