server:
  port: 8081

spring:
  cloud:
    name: gateway-service
    gateway:
      routes:
        - id: demo-one
          uri: http://library:8082
          predicates:
            - Path=/**
#          predicates:
#            - Path=/api/user/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
  redis:
    port: 6379
    host: redis

