server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
    gateway:
      routes:
        - id: demo-one
          uri: lb://library-service
          predicates:
            - Path=/**
#          predicates:
#            - Path=/api/user/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
  redis:
    port: 6379
    host: ${REDIS_HOST:localhost}


#rootLogger:
#  level: DEBUG
#  appenders:
#    - console
#
## 配置控制台输出
#appenders:
#  - type: console
#    name: CONSOLE
#    target: System.out
#    layout:
#      type: pattern
#      pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n"