server:
  port: 8081
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
    gateway:
      routes:
        - id: demo-one
          uri: http://139.224.188.165:8848
          predicates:
            - Path=/**
#          predicates:
#            - Path=/api/user/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
  redis:
    port: 6379
    host: redis


#rootLogger:
#  level: DEBUG
#  appenders:
#    - console
#
## 配置控制台输出
#appenders:
#  - type: console
#    name: CONSOLE
#    target: System.out
#    layout:
#      type: pattern
#      pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n"