server:
  port: 8081

spring:
  application:
    name: gateway-service
    gateway:
      routes:
        - id: demo-one
          uri: http://library:8082
          predicates:
            - Path=/**
#          predicates:
#            - Path=/api/user/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
  redis:
    port: 6379
    host: redis


#rootLogger:
#  level: DEBUG
#  appenders:
#    - console
#
## 配置控制台输出
#appenders:
#  - type: console
#    name: CONSOLE
#    target: System.out
#    layout:
#      type: pattern
#      pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n"